### model
model_name_or_path: <your model path>

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
seed: 123

### dataset
dataset: wai_each_question_exp_fold4
# packing: true
template: llama3
cutoff_len: 8192
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: <your output path>
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-8
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
optim: adamw_torch

### eval
#do_eval: False
val_size: 0


# command:
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup llamafactory-cli train examples/train_lora/llama3_full_sft_wai_each_question.yaml >llama3_full_sft_1e8_epoch10_wai_each_question_exp_fold4_seed123.log 2>&1 &



